import { useEffect, useMemo, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { supabase } from '../lib/supabase.js'
import { useAuth } from '../context/AuthContext.jsx'
import { chargeResidualCents, effectiveAmicaliste, formatMoney, householdBalanceCents } from '../lib/finance.js'
import { optimizeImageFile } from '../lib/mediaStorage.js'
import { PageTitle } from './Actualites.jsx'
import '../finance-households.css'

const categories={meal:'Repas',drinks:'Consommations',activity:'Activité / sortie',adjustment:'Régularisation',other:'Autre',membership:'Cotisation amicaliste'}
const safeName=(name='ticket').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').toLowerCase()

export default function AdminTreasury(){
 const {user,isAdmin,loading:authLoading}=useAuth()
 const [households,setHouseholds]=useState([]),[members,setMembers]=useState([]),[profiles,setProfiles]=useState([]),[charges,setCharges]=useState([]),[payments,setPayments]=useState([]),[allocations,setAllocations]=useState([]),[entries,setEntries]=useState([]),[events,setEvents]=useState([]),[settings,setSettings]=useState(null)
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [bankDraft,setBankDraft]=useState({bank_name:'',account_name:'',iban:'',bic:''})
 const [chargeForm,setChargeForm]=useState({household_id:'',household_member_id:'',event_id:'',category:'drinks',label:'',amount:''})
 const [expenseForm,setExpenseForm]=useState({label:'',amount:'',payment_method:'card',advanced_by:'',event_id:'',note:''}),[receipt,setReceipt]=useState(null)

 const load=async()=>{setLoading(true);setError('');const [h,m,p,c,pay,t,e,s]=await Promise.all([supabase.from('households').select('*').order('name'),supabase.from('household_members').select('*').order('display_name'),supabase.from('profiles').select('id,full_name,email,is_amicaliste,membership_valid_until').order('full_name'),supabase.from('household_charges').select('*').order('created_at',{ascending:false}),supabase.from('household_payments').select('*').order('created_at',{ascending:false}),supabase.from('treasury_entries').select('*').order('created_at',{ascending:false}).limit(300),supabase.from('events').select('id,title,starts_at,all_day,pricing_enabled,member_meal_cents,nonmember_meal_cents,child_prices').order('starts_at',{ascending:false}).limit(100),supabase.from('association_settings').select('*').eq('id',1).single()]);const first=[h.error,m.error,p.error,c.error,pay.error,t.error,e.error,s.error].find(Boolean);if(first)setError(first.message||'Chargement incomplet.');const payRows=pay.data||[];const a=payRows.length?await supabase.from('household_payment_allocations').select('*').in('payment_id',payRows.map(x=>x.id)):{data:[]};setHouseholds(h.data||[]);setMembers(m.data||[]);setProfiles(p.data||[]);setCharges(c.data||[]);setPayments(payRows);setAllocations(a.data||[]);setEntries(t.data||[]);setEvents(e.data||[]);setSettings(s.data||null);setBankDraft({bank_name:s.data?.bank_name||'',account_name:s.data?.account_name||'',iban:s.data?.iban||'',bic:s.data?.bic||''});setChargeForm(f=>({...f,household_id:f.household_id||h.data?.[0]?.id||''}));setLoading(false)}
 useEffect(()=>{if(isAdmin)load();else if(!authLoading)setLoading(false)},[isAdmin,authLoading]);if(!authLoading&&!isAdmin)return <Navigate to="/" replace/>
 const profileById=useMemo(()=>Object.fromEntries(profiles.map(p=>[p.id,p])),[profiles]),memberById=useMemo(()=>Object.fromEntries(members.map(m=>[m.id,m])),[members]),householdById=useMemo(()=>Object.fromEntries(households.map(h=>[h.id,h])),[households])
 const balanceByHousehold=useMemo(()=>Object.fromEntries(households.map(h=>[h.id,householdBalanceCents(charges.filter(c=>c.household_id===h.id),allocations,payments)])),[households,charges,allocations,payments])
 const totalDue=Object.values(balanceByHousehold).reduce((s,v)=>s+v,0),pendingPayments=payments.filter(p=>p.status==='declared'),pendingAdvances=entries.filter(e=>e.status==='pending'&&e.payment_method==='personal_advance')
 const settled=entries.filter(e=>e.status==='settled'),cashBalance=settled.reduce((sum,e)=>e.payment_method==='cash'?sum+(e.kind==='income'?e.amount_cents:-e.amount_cents):sum,0),recordedBalance=settled.reduce((sum,e)=>sum+(e.kind==='income'?e.amount_cents:-e.amount_cents),0)
 const selectedHouseholdMembers=members.filter(m=>m.household_id===chargeForm.household_id),selectedEvent=events.find(e=>e.id===chargeForm.event_id),selectedMember=memberById[chargeForm.household_member_id]
 useEffect(()=>{if(chargeForm.category!=='meal'||!selectedEvent?.pricing_enabled||!selectedMember)return;let cents=0;if(selectedMember.member_type==='child')cents=Number(selectedEvent.child_prices?.[selectedMember.age_category]||0);else{const p=profileById[selectedMember.user_id];cents=effectiveAmicaliste(p)?Number(selectedEvent.member_meal_cents||0):Number(selectedEvent.nonmember_meal_cents||0)}setChargeForm(f=>({...f,amount:(cents/100).toFixed(2),label:f.label||`Repas · ${selectedEvent.title} · ${selectedMember.display_name}`}))},[chargeForm.category,chargeForm.event_id,chargeForm.household_member_id])
 const saveBank=async()=>{setBusy(true);const payload={bank_name:bankDraft.bank_name.trim()||null,account_name:bankDraft.account_name.trim()||null,iban:bankDraft.iban.replace(/\s+/g,'').toUpperCase()||null,bic:bankDraft.bic.replace(/\s+/g,'').toUpperCase()||null,updated_by:user.id,updated_at:new Date().toISOString()};const {error:e}=await supabase.from('association_settings').update(payload).eq('id',1);if(e)setError(e.message);else{setSuccess('Coordonnées bancaires enregistrées.');await load()}setBusy(false)}
 const addCharge=async(event)=>{event.preventDefault();const amount=Math.round(Number(String(chargeForm.amount).replace(',','.'))*100);if(!chargeForm.household_id||!chargeForm.label.trim()||amount<=0)return setError('Complétez le foyer, le libellé et le montant.');setBusy(true);const member=memberById[chargeForm.household_member_id];const {error:e}=await supabase.from('household_charges').insert({household_id:chargeForm.household_id,household_member_id:member?.id||null,user_id:member?.user_id||null,event_id:chargeForm.event_id||null,category:chargeForm.category,label:chargeForm.label.trim(),amount_cents:amount,created_by:user.id});if(e)setError(e.message);else{setSuccess('Dette ajoutée au foyer.');setChargeForm(f=>({...f,label:'',amount:'',household_member_id:''}));await load()}setBusy(false)}
 const cancelCharge=async(charge)=>{if(!window.confirm(`Annuler « ${charge.label} » ? L’écriture restera visible dans l’historique.`))return;setBusy(true);const {error:e}=await supabase.from('household_charges').update({status:'cancelled',cancelled_by:user.id,cancelled_at:new Date().toISOString()}).eq('id',charge.id);if(e)setError(e.message);else{setSuccess('Charge annulée.');await load()}setBusy(false)}
 const confirmPayment=async(payment)=>{if(!window.confirm(`Confirmer la réception de ${formatMoney(payment.amount_cents)} · ${payment.reference} ?`))return;setBusy(true);const {error:e}=await supabase.rpc('confirm_household_payment',{p_payment_id:payment.id});if(e)setError(e.message);else{setSuccess('Paiement confirmé et dettes rapprochées.');await load()}setBusy(false)}
 const cashSettle=async(householdId)=>{const ids=charges.filter(c=>c.household_id===householdId&&c.status==='open'&&chargeResidualCents(c,allocations,payments)>0).map(c=>c.id);if(!ids.length)return;if(!window.confirm(`Enregistrer en espèces le règlement complet de ${formatMoney(balanceByHousehold[householdId])} ?`))return;setBusy(true);const {error:e}=await supabase.rpc('admin_record_household_payment',{p_household_id:householdId,p_charge_ids:ids,p_method:'cash',p_note:'Encaissement espèces enregistré par le trésorier'});if(e)setError(e.message);else{setSuccess('Paiement espèces enregistré.');await load()}setBusy(false)}
 const addExpense=async(event)=>{event.preventDefault();const amount=Math.round(Number(String(expenseForm.amount).replace(',','.'))*100);if(!expenseForm.label.trim()||amount<=0)return setError('Indiquez un libellé et un montant.');if(expenseForm.payment_method==='personal_advance'&&!expenseForm.advanced_by)return setError('Indiquez la personne qui a avancé la dépense.');setBusy(true);setError('');const status=expenseForm.payment_method==='personal_advance'?'pending':'settled';const {data:row,error:e}=await supabase.from('treasury_entries').insert({kind:'expense',amount_cents:amount,label:expenseForm.label.trim(),event_id:expenseForm.event_id||null,payment_method:expenseForm.payment_method,advanced_by:expenseForm.payment_method==='personal_advance'?expenseForm.advanced_by:null,status,note:expenseForm.note.trim()||null,created_by:user.id,settled_by:status==='settled'?user.id:null,settled_at:status==='settled'?new Date().toISOString():null}).select('*').single();if(e){setError(e.message);setBusy(false);return}let warning='';if(receipt&&row){try{const file=receipt.type.startsWith('image/')?await optimizeImageFile(receipt,{maxDimension:1600,quality:.8}):receipt;const path=`treasury/${row.id}/${Date.now()}-${safeName(file.name)}`;const {error:up}=await supabase.storage.from('content').upload(path,file,{contentType:file.type||undefined});if(up)throw up;await supabase.from('treasury_entries').update({receipt_storage_provider:'supabase',receipt_storage_path:path,receipt_file_name:file.name}).eq('id',row.id)}catch(err){warning=' Dépense enregistrée, mais le justificatif n’a pas pu être envoyé.'}}setSuccess(`Dépense enregistrée.${warning}`);setExpenseForm({label:'',amount:'',payment_method:'card',advanced_by:'',event_id:'',note:''});setReceipt(null);const input=document.getElementById('treasury-receipt');if(input)input.value='';await load();setBusy(false)}
 const settleAdvance=async(entry)=>{if(!window.confirm(`Marquer ${formatMoney(entry.amount_cents)} remboursés à ${profileById[entry.advanced_by]?.full_name||'ce membre'} ?`))return;setBusy(true);const {error:e}=await supabase.from('treasury_entries').update({status:'settled',settled_by:user.id,settled_at:new Date().toISOString()}).eq('id',entry.id);if(e)setError(e.message);else{setSuccess('Avance marquée comme remboursée.');await load()}setBusy(false)}
 const openReceipt=async(entry)=>{if(!entry.receipt_storage_path)return;const {data,error:e}=await supabase.storage.from('content').createSignedUrl(entry.receipt_storage_path,600);if(e)setError(e.message);else window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 const householdOpenCharges=(id)=>charges.filter(c=>c.household_id===id&&c.status==='open'&&chargeResidualCents(c,allocations,payments)>0)
 return <div className="admin-treasury-page"><PageTitle eyebrow="Administration" title="Trésorerie" text="Centralisez les dettes des foyers, les règlements, les dépenses du bureau, les avances et les justificatifs."/>{error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success}</div>}{loading?<div className="skeleton-card tall"/>:<><div className="treasury-kpi-grid"><article className="treasury-kpi"><span>Dettes des foyers</span><strong>{formatMoney(totalDue)}</strong></article><article className="treasury-kpi"><span>Virements à vérifier</span><strong>{pendingPayments.length}</strong></article><article className="treasury-kpi"><span>Avances à rembourser</span><strong>{formatMoney(pendingAdvances.reduce((s,e)=>s+e.amount_cents,0))}</strong></article><article className="treasury-kpi"><span>Flux net enregistré</span><strong>{formatMoney(recordedBalance)}</strong><small>Caisse espèces : {formatMoney(cashBalance)}</small></article></div>
 <section className="text-panel"><div className="finance-heading"><div><span className="eyebrow">Compte bancaire</span><h2>Caisse d’Épargne / RIB de l’Amicale</h2></div></div><div className="admin-finance-form"><div className="form-row"><label>Banque<input value={bankDraft.bank_name} onChange={e=>setBankDraft({...bankDraft,bank_name:e.target.value})} placeholder="Caisse d’Épargne"/></label><label>Nom du bénéficiaire<input value={bankDraft.account_name} onChange={e=>setBankDraft({...bankDraft,account_name:e.target.value})} placeholder="Amicale DANZ Antilles"/></label></div><label>IBAN<input value={bankDraft.iban} onChange={e=>setBankDraft({...bankDraft,iban:e.target.value})} placeholder="FR…"/></label><label>BIC<input value={bankDraft.bic} onChange={e=>setBankDraft({...bankDraft,bic:e.target.value})}/></label><button type="button" className="primary-button" disabled={busy} onClick={saveBank}>Enregistrer le RIB</button></div></section>
 {pendingPayments.length>0&&<section className="text-panel"><div className="finance-heading"><div><span className="eyebrow">Rapprochement</span><h2>Virements déclarés à vérifier</h2></div></div><div className="treasury-list">{pendingPayments.map(p=><div className="treasury-row" key={p.id}><div><strong>{householdById[p.household_id]?.name||'Foyer'} · {p.reference}</strong><small>Déclaré le {p.declared_at?new Date(p.declared_at).toLocaleString('fr-FR'):'—'}</small></div><b>{formatMoney(p.amount_cents)}</b><button type="button" className="primary-button" disabled={busy} onClick={()=>confirmPayment(p)}>Confirmer reçu</button></div>)}</div></section>}
 <div className="admin-finance-grid"><section className="text-panel"><h2>Ajouter une dette</h2><form className="admin-finance-form" onSubmit={addCharge}><label>Foyer<select value={chargeForm.household_id} onChange={e=>setChargeForm({...chargeForm,household_id:e.target.value,household_member_id:''})}>{households.map(h=><option value={h.id} key={h.id}>{h.name} · {formatMoney(balanceByHousehold[h.id]||0)}</option>)}</select></label><label>Personne concernée (facultatif)<select value={chargeForm.household_member_id} onChange={e=>setChargeForm({...chargeForm,household_member_id:e.target.value})}><option value="">Foyer entier</option>{selectedHouseholdMembers.map(m=><option key={m.id} value={m.id}>{m.display_name}{m.member_type==='child'?` · ${m.age_category}`:''}</option>)}</select></label><label>Événement (facultatif)<select value={chargeForm.event_id} onChange={e=>setChargeForm({...chargeForm,event_id:e.target.value,label:''})}><option value="">Aucun</option>{events.map(ev=><option key={ev.id} value={ev.id}>{ev.title}</option>)}</select></label><label>Catégorie<select value={chargeForm.category} onChange={e=>setChargeForm({...chargeForm,category:e.target.value})}>{Object.entries(categories).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Libellé<input required value={chargeForm.label} onChange={e=>setChargeForm({...chargeForm,label:e.target.value})} placeholder="Ex. Boissons · repas du 12 octobre"/></label><label>Montant (€)<input required inputMode="decimal" value={chargeForm.amount} onChange={e=>setChargeForm({...chargeForm,amount:e.target.value})}/></label>{selectedEvent?.pricing_enabled&&chargeForm.category==='meal'&&<small>Tarif proposé automatiquement d’après le statut amicaliste ou la catégorie d’âge. Il reste modifiable avant enregistrement.</small>}<button className="primary-button" disabled={busy}>Ajouter la dette</button></form></section>
 <section className="text-panel"><h2>Enregistrer une dépense</h2><form className="admin-finance-form" onSubmit={addExpense}><label>Libellé<input required value={expenseForm.label} onChange={e=>setExpenseForm({...expenseForm,label:e.target.value})} placeholder="Courses, boissons, location…"/></label><label>Montant (€)<input required inputMode="decimal" value={expenseForm.amount} onChange={e=>setExpenseForm({...expenseForm,amount:e.target.value})}/></label><label>Payé avec<select value={expenseForm.payment_method} onChange={e=>setExpenseForm({...expenseForm,payment_method:e.target.value})}><option value="card">Carte de l’Amicale</option><option value="bank_transfer">Virement de l’Amicale</option><option value="cash">Caisse espèces</option><option value="personal_advance">Avance personnelle d’un membre</option></select></label>{expenseForm.payment_method==='personal_advance'&&<label>Avancé par<select required value={expenseForm.advanced_by} onChange={e=>setExpenseForm({...expenseForm,advanced_by:e.target.value})}><option value="">Choisir…</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.full_name||p.email}</option>)}</select></label>}<label>Événement (facultatif)<select value={expenseForm.event_id} onChange={e=>setExpenseForm({...expenseForm,event_id:e.target.value})}><option value="">Aucun</option>{events.map(ev=><option key={ev.id} value={ev.id}>{ev.title}</option>)}</select></label><label>Note<textarea rows="2" value={expenseForm.note} onChange={e=>setExpenseForm({...expenseForm,note:e.target.value})}/></label><label>Ticket / facture (facultatif)<input id="treasury-receipt" type="file" accept="image/*,.pdf" onChange={e=>setReceipt(e.target.files?.[0]||null)}/></label><button className="primary-button" disabled={busy}>Enregistrer la dépense</button></form></section></div>
 <section className="text-panel"><div className="finance-heading"><div><span className="eyebrow">Foyers</span><h2>Soldes et encaissements</h2></div></div><div className="treasury-list">{households.map(h=>{const due=balanceByHousehold[h.id]||0;return <div className="treasury-row" key={h.id}><div><strong>{h.name}</strong><small>{householdOpenCharges(h.id).length} charge{householdOpenCharges(h.id).length>1?'s':''} ouverte{householdOpenCharges(h.id).length>1?'s':''}</small></div><b>{formatMoney(due)}</b>{due>0&&<button type="button" className="ghost-button" disabled={busy} onClick={()=>cashSettle(h.id)}>Encaisser en espèces</button>}</div>})}</div></section>
 {pendingAdvances.length>0&&<section className="text-panel"><h2>Avances personnelles à rembourser</h2><div className="treasury-list">{pendingAdvances.map(e=><div className="treasury-row is-expense" key={e.id}><div><strong>{e.label}</strong><small>{profileById[e.advanced_by]?.full_name||'Membre du bureau'} · {new Date(e.created_at).toLocaleDateString('fr-FR')}</small></div><b>{formatMoney(e.amount_cents)}</b><button type="button" className="primary-button" disabled={busy} onClick={()=>settleAdvance(e)}>Marquer remboursé</button></div>)}</div></section>}
 <section className="text-panel"><h2>Dernières écritures de trésorerie</h2><div className="treasury-list">{entries.slice(0,100).map(e=><div className={`treasury-row ${e.kind==='income'?'is-income':'is-expense'}`} key={e.id}><div><strong>{e.label}</strong><small>{e.payment_method} · {e.status==='pending'?'à rembourser':'réglé'} · {new Date(e.created_at).toLocaleString('fr-FR')}</small></div><b>{formatMoney(e.amount_cents)}</b>{e.receipt_storage_path&&<button type="button" className="ghost-button" onClick={()=>openReceipt(e)}>Justificatif</button>}</div>)}</div></section></>}</div>
}
