-- Assistant DANZ V32 : proprietaire nominatif, confirmation serveur, preferences visuelles.
create table if not exists private.danz_assistant_owner (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);
alter table private.danz_assistant_owner enable row level security;
insert into private.danz_assistant_owner(user_id)
  select id from public.profiles where active=true and role='admin' and is_treasurer=true
  on conflict(user_id) do nothing;

create or replace function public.danz_assistant_access()
returns boolean language sql stable security definer set search_path=''
as $$
  select auth.uid() is not null and private.is_treasurer()
  and exists(select 1 from private.danz_assistant_owner
             where user_id=auth.uid() and enabled=true);
$$;
revoke all on function public.danz_assistant_access() from public,anon;
grant execute on function public.danz_assistant_access() to authenticated;

create table if not exists public.danz_assistant_actions (
  id uuid primary key default gen_random_uuid(),
  requested_by uuid not null references public.profiles(id),
  action_type text not null,
  payload jsonb not null,
  summary text not null,
  status text not null default 'pending'
    check(status in('pending','executing','completed','failed','rejected')),
  expires_at timestamptz not null default(now()+interval '15 minutes'),
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  error_message text
);
create index if not exists danz_assistant_actions_owner_recent
  on public.danz_assistant_actions(requested_by,created_at desc);
alter table public.danz_assistant_actions enable row level security;
revoke all on public.danz_assistant_actions from public,anon,authenticated;
grant all on public.danz_assistant_actions to service_role;

create table if not exists public.danz_assistant_usage(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);
create index if not exists danz_assistant_usage_owner_time
  on public.danz_assistant_usage(user_id,created_at desc);
alter table public.danz_assistant_usage enable row level security;
revoke all on public.danz_assistant_usage from public,anon,authenticated;
grant all on public.danz_assistant_usage to service_role;

create table if not exists public.danz_assistant_technical_requests(
  id uuid primary key default gen_random_uuid(),
  requested_by uuid not null references public.profiles(id),
  description text not null check(char_length(description) between 10 and 3000),
  status text not null default 'a_preparer',
  created_at timestamptz not null default now()
);
alter table public.danz_assistant_technical_requests enable row level security;
revoke all on public.danz_assistant_technical_requests from public,anon,authenticated;
grant all on public.danz_assistant_technical_requests to service_role;

create table if not exists public.site_preferences(
  id smallint primary key default 1 check(id=1),
  accent_color text not null default '#0b5165'
    check(accent_color ~ '^#[0-9a-fA-F]{6}$'),
  home_subtitle text not null default
    'Publications, rendez-vous, recensements et vie de votre foyer.'
    check(char_length(home_subtitle) between 5 and 220),
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);
insert into public.site_preferences(id) values(1) on conflict(id) do nothing;
alter table public.site_preferences enable row level security;
drop policy if exists "members read site preferences" on public.site_preferences;
create policy "members read site preferences" on public.site_preferences
  for select to authenticated using(private.is_active_member());
drop policy if exists "admins manage site preferences" on public.site_preferences;
create policy "admins manage site preferences" on public.site_preferences
  for all to authenticated using(private.is_admin())
  with check(private.is_admin());
revoke all on public.site_preferences from public,anon;
grant select,update on public.site_preferences to authenticated;
grant all on public.site_preferences to service_role;
